networks:
    lernsax_sync:
      name: lernsax_sync
      external: true

services:
  apns_bridge:
    build: "./apns_bridge/Dockerfile"
    container_name: lernsax_apns
    env_file:
      - .env
    networks:
      - lernsax_sync
  sync_server:
    build: "./sync-server/Dockerfile"
    container_name: lernsax_sync
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./files:/files:ro
      - lernsax_git:/git
    networks:
      - lernsax_sync

volumes:
  lernsax_git:
    name: lernsax_git
    external: true