networks:
    lernsax:
      name: lernsax
      external: true

services:
  app:
    build: .
    container_name: lernsax_history
    env_file:
      - .env
    volumes:
      - ./files:/app/files:ro
    networks:
      - lernsax