version: '3'
networks:
    lernsax:
        external: true
services:
    server:
        image: gitea/gitea:1.16.3
        container_name: gitea
        environment:
            - USER_UID=1000
            - USER_GID=1000
        restart: always
        networks:
            - lernsax
        volumes:
            - data:/data
            - /etc/timezone:/etc/timezone:ro
            - /etc/localtime:/etc/localtime:ro
        ports:
            - '3001:3000'
#            - '222:22'
volumes:
  data:
    external: true
    name: git-data